//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusWeb.ZeusService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoDTO", Namespace="http://schemas.datacontract.org/2004/07/ZeusServices")]
    [System.SerializableAttribute()]
    public partial class EmpleadoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string depar_nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string grp_nombre_cargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string grp_nombre_encargadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short usr_cargo_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short usr_departamento_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_fecha_creacion_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_fecha_ultimo_ingresoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_fechanacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] usr_fotografiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short usr_grupo_encargado_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_identificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_loginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> usr_salarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_telefonoFijoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usr_telefonoMovilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Login {
            get {
                return this.ID_LoginField;
            }
            set {
                if ((this.ID_LoginField.Equals(value) != true)) {
                    this.ID_LoginField = value;
                    this.RaisePropertyChanged("ID_Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string depar_nombre {
            get {
                return this.depar_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.depar_nombreField, value) != true)) {
                    this.depar_nombreField = value;
                    this.RaisePropertyChanged("depar_nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grp_nombre_cargo {
            get {
                return this.grp_nombre_cargoField;
            }
            set {
                if ((object.ReferenceEquals(this.grp_nombre_cargoField, value) != true)) {
                    this.grp_nombre_cargoField = value;
                    this.RaisePropertyChanged("grp_nombre_cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grp_nombre_encargado {
            get {
                return this.grp_nombre_encargadoField;
            }
            set {
                if ((object.ReferenceEquals(this.grp_nombre_encargadoField, value) != true)) {
                    this.grp_nombre_encargadoField = value;
                    this.RaisePropertyChanged("grp_nombre_encargado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_apellidos {
            get {
                return this.usr_apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_apellidosField, value) != true)) {
                    this.usr_apellidosField = value;
                    this.RaisePropertyChanged("usr_apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short usr_cargo_ID {
            get {
                return this.usr_cargo_IDField;
            }
            set {
                if ((this.usr_cargo_IDField.Equals(value) != true)) {
                    this.usr_cargo_IDField = value;
                    this.RaisePropertyChanged("usr_cargo_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short usr_departamento_ID {
            get {
                return this.usr_departamento_IDField;
            }
            set {
                if ((this.usr_departamento_IDField.Equals(value) != true)) {
                    this.usr_departamento_IDField = value;
                    this.RaisePropertyChanged("usr_departamento_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_direccion {
            get {
                return this.usr_direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_direccionField, value) != true)) {
                    this.usr_direccionField = value;
                    this.RaisePropertyChanged("usr_direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_email {
            get {
                return this.usr_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_emailField, value) != true)) {
                    this.usr_emailField = value;
                    this.RaisePropertyChanged("usr_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_fecha_creacion_usuario {
            get {
                return this.usr_fecha_creacion_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_fecha_creacion_usuarioField, value) != true)) {
                    this.usr_fecha_creacion_usuarioField = value;
                    this.RaisePropertyChanged("usr_fecha_creacion_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_fecha_ultimo_ingreso {
            get {
                return this.usr_fecha_ultimo_ingresoField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_fecha_ultimo_ingresoField, value) != true)) {
                    this.usr_fecha_ultimo_ingresoField = value;
                    this.RaisePropertyChanged("usr_fecha_ultimo_ingreso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_fechanacimiento {
            get {
                return this.usr_fechanacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_fechanacimientoField, value) != true)) {
                    this.usr_fechanacimientoField = value;
                    this.RaisePropertyChanged("usr_fechanacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] usr_fotografia {
            get {
                return this.usr_fotografiaField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_fotografiaField, value) != true)) {
                    this.usr_fotografiaField = value;
                    this.RaisePropertyChanged("usr_fotografia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short usr_grupo_encargado_ID {
            get {
                return this.usr_grupo_encargado_IDField;
            }
            set {
                if ((this.usr_grupo_encargado_IDField.Equals(value) != true)) {
                    this.usr_grupo_encargado_IDField = value;
                    this.RaisePropertyChanged("usr_grupo_encargado_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_identificacion {
            get {
                return this.usr_identificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_identificacionField, value) != true)) {
                    this.usr_identificacionField = value;
                    this.RaisePropertyChanged("usr_identificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_login {
            get {
                return this.usr_loginField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_loginField, value) != true)) {
                    this.usr_loginField = value;
                    this.RaisePropertyChanged("usr_login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_nombres {
            get {
                return this.usr_nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_nombresField, value) != true)) {
                    this.usr_nombresField = value;
                    this.RaisePropertyChanged("usr_nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> usr_salario {
            get {
                return this.usr_salarioField;
            }
            set {
                if ((this.usr_salarioField.Equals(value) != true)) {
                    this.usr_salarioField = value;
                    this.RaisePropertyChanged("usr_salario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_telefonoFijo {
            get {
                return this.usr_telefonoFijoField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_telefonoFijoField, value) != true)) {
                    this.usr_telefonoFijoField = value;
                    this.RaisePropertyChanged("usr_telefonoFijo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_telefonoMovil {
            get {
                return this.usr_telefonoMovilField;
            }
            set {
                if ((object.ReferenceEquals(this.usr_telefonoMovilField, value) != true)) {
                    this.usr_telefonoMovilField = value;
                    this.RaisePropertyChanged("usr_telefonoMovil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbicacionDTO", Namespace="http://schemas.datacontract.org/2004/07/ZeusServices")]
    [System.SerializableAttribute()]
    public partial class UbicacionDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BearingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_CoordenadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_Usuario_UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TiempoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> VelocidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Bearing {
            get {
                return this.BearingField;
            }
            set {
                if ((this.BearingField.Equals(value) != true)) {
                    this.BearingField = value;
                    this.RaisePropertyChanged("Bearing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Coordenada {
            get {
                return this.ID_CoordenadaField;
            }
            set {
                if ((this.ID_CoordenadaField.Equals(value) != true)) {
                    this.ID_CoordenadaField = value;
                    this.RaisePropertyChanged("ID_Coordenada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Usuario_Ubicacion {
            get {
                return this.ID_Usuario_UbicacionField;
            }
            set {
                if ((this.ID_Usuario_UbicacionField.Equals(value) != true)) {
                    this.ID_Usuario_UbicacionField = value;
                    this.RaisePropertyChanged("ID_Usuario_Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((this.LatitudField.Equals(value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Usuario {
            get {
                return this.Nombre_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_UsuarioField, value) != true)) {
                    this.Nombre_UsuarioField = value;
                    this.RaisePropertyChanged("Nombre_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precision {
            get {
                return this.PrecisionField;
            }
            set {
                if ((this.PrecisionField.Equals(value) != true)) {
                    this.PrecisionField = value;
                    this.RaisePropertyChanged("Precision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tiempo {
            get {
                return this.TiempoField;
            }
            set {
                if ((object.ReferenceEquals(this.TiempoField, value) != true)) {
                    this.TiempoField = value;
                    this.RaisePropertyChanged("Tiempo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Velocidad {
            get {
                return this.VelocidadField;
            }
            set {
                if ((this.VelocidadField.Equals(value) != true)) {
                    this.VelocidadField = value;
                    this.RaisePropertyChanged("Velocidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistorialChat", Namespace="http://schemas.datacontract.org/2004/07/ZeusServices")]
    [System.SerializableAttribute()]
    public partial class HistorialChat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmisorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ID_ChatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceptorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Emisor {
            get {
                return this.EmisorField;
            }
            set {
                if ((this.EmisorField.Equals(value) != true)) {
                    this.EmisorField = value;
                    this.RaisePropertyChanged("Emisor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_Chat {
            get {
                return this.ID_ChatField;
            }
            set {
                if ((this.ID_ChatField.Equals(value) != true)) {
                    this.ID_ChatField = value;
                    this.RaisePropertyChanged("ID_Chat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Receptor {
            get {
                return this.ReceptorField;
            }
            set {
                if ((this.ReceptorField.Equals(value) != true)) {
                    this.ReceptorField = value;
                    this.RaisePropertyChanged("Receptor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZeusService.IServiceZeus")]
    public interface IServiceZeus {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/ProbarConexionWs", ReplyAction="http://tempuri.org/IServiceZeus/ProbarConexionWsResponse")]
        string ProbarConexionWs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/ProbarConexionWs", ReplyAction="http://tempuri.org/IServiceZeus/ProbarConexionWsResponse")]
        System.Threading.Tasks.Task<string> ProbarConexionWsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/VerificarLogin", ReplyAction="http://tempuri.org/IServiceZeus/VerificarLoginResponse")]
        ZeusWeb.ZeusService.EmpleadoDTO VerificarLogin(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/VerificarLogin", ReplyAction="http://tempuri.org/IServiceZeus/VerificarLoginResponse")]
        System.Threading.Tasks.Task<ZeusWeb.ZeusService.EmpleadoDTO> VerificarLoginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/AgregarEmpleado", ReplyAction="http://tempuri.org/IServiceZeus/AgregarEmpleadoResponse")]
        void AgregarEmpleado(
                    string login, 
                    string password, 
                    long fechaPassword, 
                    long fechaUltimoIngreso, 
                    long fechaCreacionUsuario, 
                    string nombres, 
                    string apellidos, 
                    string direccion, 
                    decimal salario, 
                    string telefonoMovil, 
                    string telefonoFijo, 
                    string email, 
                    short departamentoID, 
                    byte[] foto, 
                    string identificacion, 
                    short cargoID, 
                    short grupoEncargadoID, 
                    long fechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/AgregarEmpleado", ReplyAction="http://tempuri.org/IServiceZeus/AgregarEmpleadoResponse")]
        System.Threading.Tasks.Task AgregarEmpleadoAsync(
                    string login, 
                    string password, 
                    long fechaPassword, 
                    long fechaUltimoIngreso, 
                    long fechaCreacionUsuario, 
                    string nombres, 
                    string apellidos, 
                    string direccion, 
                    decimal salario, 
                    string telefonoMovil, 
                    string telefonoFijo, 
                    string email, 
                    short departamentoID, 
                    byte[] foto, 
                    string identificacion, 
                    short cargoID, 
                    short grupoEncargadoID, 
                    long fechaNacimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/ListaEmpleadosAsignados", ReplyAction="http://tempuri.org/IServiceZeus/ListaEmpleadosAsignadosResponse")]
        ZeusWeb.ZeusService.EmpleadoDTO[] ListaEmpleadosAsignados(int ID_Grupo_Encargado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/ListaEmpleadosAsignados", ReplyAction="http://tempuri.org/IServiceZeus/ListaEmpleadosAsignadosResponse")]
        System.Threading.Tasks.Task<ZeusWeb.ZeusService.EmpleadoDTO[]> ListaEmpleadosAsignadosAsync(int ID_Grupo_Encargado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/ListaGrupoDeTrabajoConSupervisor", ReplyAction="http://tempuri.org/IServiceZeus/ListaGrupoDeTrabajoConSupervisorResponse")]
        ZeusWeb.ZeusService.EmpleadoDTO[] ListaGrupoDeTrabajoConSupervisor(int ID_Grupo_Perteneciente, int loginExcluir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/ListaGrupoDeTrabajoConSupervisor", ReplyAction="http://tempuri.org/IServiceZeus/ListaGrupoDeTrabajoConSupervisorResponse")]
        System.Threading.Tasks.Task<ZeusWeb.ZeusService.EmpleadoDTO[]> ListaGrupoDeTrabajoConSupervisorAsync(int ID_Grupo_Perteneciente, int loginExcluir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/SubirCoordenadasEmpleados", ReplyAction="http://tempuri.org/IServiceZeus/SubirCoordenadasEmpleadosResponse")]
        void SubirCoordenadasEmpleados(int ID, decimal Latitud, decimal Longitud, System.Nullable<decimal> Velocidad, decimal Precision, decimal Bearing, string tiempo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/SubirCoordenadasEmpleados", ReplyAction="http://tempuri.org/IServiceZeus/SubirCoordenadasEmpleadosResponse")]
        System.Threading.Tasks.Task SubirCoordenadasEmpleadosAsync(int ID, decimal Latitud, decimal Longitud, System.Nullable<decimal> Velocidad, decimal Precision, decimal Bearing, string tiempo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/BajarCoordenadasEmpleados", ReplyAction="http://tempuri.org/IServiceZeus/BajarCoordenadasEmpleadosResponse")]
        ZeusWeb.ZeusService.UbicacionDTO[] BajarCoordenadasEmpleados(long fechaInicial, long fechaFinal, int[] persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/BajarCoordenadasEmpleados", ReplyAction="http://tempuri.org/IServiceZeus/BajarCoordenadasEmpleadosResponse")]
        System.Threading.Tasks.Task<ZeusWeb.ZeusService.UbicacionDTO[]> BajarCoordenadasEmpleadosAsync(long fechaInicial, long fechaFinal, int[] persona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/ListarMensajes", ReplyAction="http://tempuri.org/IServiceZeus/ListarMensajesResponse")]
        ZeusWeb.ZeusService.HistorialChat[] ListarMensajes(int emisor, int receptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/ListarMensajes", ReplyAction="http://tempuri.org/IServiceZeus/ListarMensajesResponse")]
        System.Threading.Tasks.Task<ZeusWeb.ZeusService.HistorialChat[]> ListarMensajesAsync(int emisor, int receptor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/guardarMensajes", ReplyAction="http://tempuri.org/IServiceZeus/guardarMensajesResponse")]
        void guardarMensajes(int emisor, int receptor, string mensaje, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceZeus/guardarMensajes", ReplyAction="http://tempuri.org/IServiceZeus/guardarMensajesResponse")]
        System.Threading.Tasks.Task guardarMensajesAsync(int emisor, int receptor, string mensaje, System.DateTime fecha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceZeusChannel : ZeusWeb.ZeusService.IServiceZeus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceZeusClient : System.ServiceModel.ClientBase<ZeusWeb.ZeusService.IServiceZeus>, ZeusWeb.ZeusService.IServiceZeus {
        
        public ServiceZeusClient() {
        }
        
        public ServiceZeusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceZeusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceZeusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceZeusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ProbarConexionWs() {
            return base.Channel.ProbarConexionWs();
        }
        
        public System.Threading.Tasks.Task<string> ProbarConexionWsAsync() {
            return base.Channel.ProbarConexionWsAsync();
        }
        
        public ZeusWeb.ZeusService.EmpleadoDTO VerificarLogin(string login, string password) {
            return base.Channel.VerificarLogin(login, password);
        }
        
        public System.Threading.Tasks.Task<ZeusWeb.ZeusService.EmpleadoDTO> VerificarLoginAsync(string login, string password) {
            return base.Channel.VerificarLoginAsync(login, password);
        }
        
        public void AgregarEmpleado(
                    string login, 
                    string password, 
                    long fechaPassword, 
                    long fechaUltimoIngreso, 
                    long fechaCreacionUsuario, 
                    string nombres, 
                    string apellidos, 
                    string direccion, 
                    decimal salario, 
                    string telefonoMovil, 
                    string telefonoFijo, 
                    string email, 
                    short departamentoID, 
                    byte[] foto, 
                    string identificacion, 
                    short cargoID, 
                    short grupoEncargadoID, 
                    long fechaNacimiento) {
            base.Channel.AgregarEmpleado(login, password, fechaPassword, fechaUltimoIngreso, fechaCreacionUsuario, nombres, apellidos, direccion, salario, telefonoMovil, telefonoFijo, email, departamentoID, foto, identificacion, cargoID, grupoEncargadoID, fechaNacimiento);
        }
        
        public System.Threading.Tasks.Task AgregarEmpleadoAsync(
                    string login, 
                    string password, 
                    long fechaPassword, 
                    long fechaUltimoIngreso, 
                    long fechaCreacionUsuario, 
                    string nombres, 
                    string apellidos, 
                    string direccion, 
                    decimal salario, 
                    string telefonoMovil, 
                    string telefonoFijo, 
                    string email, 
                    short departamentoID, 
                    byte[] foto, 
                    string identificacion, 
                    short cargoID, 
                    short grupoEncargadoID, 
                    long fechaNacimiento) {
            return base.Channel.AgregarEmpleadoAsync(login, password, fechaPassword, fechaUltimoIngreso, fechaCreacionUsuario, nombres, apellidos, direccion, salario, telefonoMovil, telefonoFijo, email, departamentoID, foto, identificacion, cargoID, grupoEncargadoID, fechaNacimiento);
        }
        
        public ZeusWeb.ZeusService.EmpleadoDTO[] ListaEmpleadosAsignados(int ID_Grupo_Encargado) {
            return base.Channel.ListaEmpleadosAsignados(ID_Grupo_Encargado);
        }
        
        public System.Threading.Tasks.Task<ZeusWeb.ZeusService.EmpleadoDTO[]> ListaEmpleadosAsignadosAsync(int ID_Grupo_Encargado) {
            return base.Channel.ListaEmpleadosAsignadosAsync(ID_Grupo_Encargado);
        }
        
        public ZeusWeb.ZeusService.EmpleadoDTO[] ListaGrupoDeTrabajoConSupervisor(int ID_Grupo_Perteneciente, int loginExcluir) {
            return base.Channel.ListaGrupoDeTrabajoConSupervisor(ID_Grupo_Perteneciente, loginExcluir);
        }
        
        public System.Threading.Tasks.Task<ZeusWeb.ZeusService.EmpleadoDTO[]> ListaGrupoDeTrabajoConSupervisorAsync(int ID_Grupo_Perteneciente, int loginExcluir) {
            return base.Channel.ListaGrupoDeTrabajoConSupervisorAsync(ID_Grupo_Perteneciente, loginExcluir);
        }
        
        public void SubirCoordenadasEmpleados(int ID, decimal Latitud, decimal Longitud, System.Nullable<decimal> Velocidad, decimal Precision, decimal Bearing, string tiempo) {
            base.Channel.SubirCoordenadasEmpleados(ID, Latitud, Longitud, Velocidad, Precision, Bearing, tiempo);
        }
        
        public System.Threading.Tasks.Task SubirCoordenadasEmpleadosAsync(int ID, decimal Latitud, decimal Longitud, System.Nullable<decimal> Velocidad, decimal Precision, decimal Bearing, string tiempo) {
            return base.Channel.SubirCoordenadasEmpleadosAsync(ID, Latitud, Longitud, Velocidad, Precision, Bearing, tiempo);
        }
        
        public ZeusWeb.ZeusService.UbicacionDTO[] BajarCoordenadasEmpleados(long fechaInicial, long fechaFinal, int[] persona) {
            return base.Channel.BajarCoordenadasEmpleados(fechaInicial, fechaFinal, persona);
        }
        
        public System.Threading.Tasks.Task<ZeusWeb.ZeusService.UbicacionDTO[]> BajarCoordenadasEmpleadosAsync(long fechaInicial, long fechaFinal, int[] persona) {
            return base.Channel.BajarCoordenadasEmpleadosAsync(fechaInicial, fechaFinal, persona);
        }
        
        public ZeusWeb.ZeusService.HistorialChat[] ListarMensajes(int emisor, int receptor) {
            return base.Channel.ListarMensajes(emisor, receptor);
        }
        
        public System.Threading.Tasks.Task<ZeusWeb.ZeusService.HistorialChat[]> ListarMensajesAsync(int emisor, int receptor) {
            return base.Channel.ListarMensajesAsync(emisor, receptor);
        }
        
        public void guardarMensajes(int emisor, int receptor, string mensaje, System.DateTime fecha) {
            base.Channel.guardarMensajes(emisor, receptor, mensaje, fecha);
        }
        
        public System.Threading.Tasks.Task guardarMensajesAsync(int emisor, int receptor, string mensaje, System.DateTime fecha) {
            return base.Channel.guardarMensajesAsync(emisor, receptor, mensaje, fecha);
        }
    }
}
