//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace Acquaint.Native.Droid
{
    using System.Runtime.Serialization;
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoDTO", Namespace="http://schemas.datacontract.org/2004/07/ZeusServices")]
    public partial class EmpleadoDTO : object
    {
		public override string ToString()
		{
			return this.usr_nombres + " " + this.usr_apellidos;
		}

        private int ID_LoginField;
        
        private string depar_nombreField;
        
        private string grp_nombre_cargoField;
        
        private string grp_nombre_encargadoField;
        
        private string usr_apellidosField;
        
        private short usr_cargo_IDField;
        
        private short usr_departamento_IDField;
        
        private string usr_direccionField;
        
        private string usr_emailField;
        
        private string usr_fecha_creacion_usuarioField;
        
        private string usr_fecha_ultimo_ingresoField;
        
        private string usr_fechanacimientoField;
        
        private byte[] usr_fotografiaField;
        
        private short usr_grupo_encargado_IDField;
        
        private string usr_identificacionField;
        
        private string usr_loginField;
        
        private string usr_nombresField;
        
        private System.Nullable<decimal> usr_salarioField;
        
        private string usr_telefonoFijoField;
        
        private string usr_telefonoMovilField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Login
        {
            get
            {
                return this.ID_LoginField;
            }
            set
            {
                this.ID_LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string depar_nombre
        {
            get
            {
                return this.depar_nombreField;
            }
            set
            {
                this.depar_nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grp_nombre_cargo
        {
            get
            {
                return this.grp_nombre_cargoField;
            }
            set
            {
                this.grp_nombre_cargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string grp_nombre_encargado
        {
            get
            {
                return this.grp_nombre_encargadoField;
            }
            set
            {
                this.grp_nombre_encargadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_apellidos
        {
            get
            {
                return this.usr_apellidosField;
            }
            set
            {
                this.usr_apellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short usr_cargo_ID
        {
            get
            {
                return this.usr_cargo_IDField;
            }
            set
            {
                this.usr_cargo_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short usr_departamento_ID
        {
            get
            {
                return this.usr_departamento_IDField;
            }
            set
            {
                this.usr_departamento_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_direccion
        {
            get
            {
                return this.usr_direccionField;
            }
            set
            {
                this.usr_direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_email
        {
            get
            {
                return this.usr_emailField;
            }
            set
            {
                this.usr_emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_fecha_creacion_usuario
        {
            get
            {
                return this.usr_fecha_creacion_usuarioField;
            }
            set
            {
                this.usr_fecha_creacion_usuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_fecha_ultimo_ingreso
        {
            get
            {
                return this.usr_fecha_ultimo_ingresoField;
            }
            set
            {
                this.usr_fecha_ultimo_ingresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_fechanacimiento
        {
            get
            {
                return this.usr_fechanacimientoField;
            }
            set
            {
                this.usr_fechanacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] usr_fotografia
        {
            get
            {
                return this.usr_fotografiaField;
            }
            set
            {
                this.usr_fotografiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short usr_grupo_encargado_ID
        {
            get
            {
                return this.usr_grupo_encargado_IDField;
            }
            set
            {
                this.usr_grupo_encargado_IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_identificacion
        {
            get
            {
                return this.usr_identificacionField;
            }
            set
            {
                this.usr_identificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_login
        {
            get
            {
                return this.usr_loginField;
            }
            set
            {
                this.usr_loginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_nombres
        {
            get
            {
                return this.usr_nombresField;
            }
            set
            {
                this.usr_nombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> usr_salario
        {
            get
            {
                return this.usr_salarioField;
            }
            set
            {
                this.usr_salarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_telefonoFijo
        {
            get
            {
                return this.usr_telefonoFijoField;
            }
            set
            {
                this.usr_telefonoFijoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usr_telefonoMovil
        {
            get
            {
                return this.usr_telefonoMovilField;
            }
            set
            {
                this.usr_telefonoMovilField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbicacionDTO", Namespace="http://schemas.datacontract.org/2004/07/ZeusServices")]
    public partial class UbicacionDTO : object
    {
        
        private decimal BearingField;
        
        private string DireccionField;
        
        private int ID_CoordenadaField;
        
        private int ID_Usuario_UbicacionField;
        
        private decimal LatitudField;
        
        private decimal LongitudField;
        
        private string Nombre_UsuarioField;
        
        private decimal PrecisionField;
        
        private string TiempoField;
        
        private System.Nullable<decimal> VelocidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Bearing
        {
            get
            {
                return this.BearingField;
            }
            set
            {
                this.BearingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Coordenada
        {
            get
            {
                return this.ID_CoordenadaField;
            }
            set
            {
                this.ID_CoordenadaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_Usuario_Ubicacion
        {
            get
            {
                return this.ID_Usuario_UbicacionField;
            }
            set
            {
                this.ID_Usuario_UbicacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Latitud
        {
            get
            {
                return this.LatitudField;
            }
            set
            {
                this.LatitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Longitud
        {
            get
            {
                return this.LongitudField;
            }
            set
            {
                this.LongitudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Usuario
        {
            get
            {
                return this.Nombre_UsuarioField;
            }
            set
            {
                this.Nombre_UsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precision
        {
            get
            {
                return this.PrecisionField;
            }
            set
            {
                this.PrecisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tiempo
        {
            get
            {
                return this.TiempoField;
            }
            set
            {
                this.TiempoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Velocidad
        {
            get
            {
                return this.VelocidadField;
            }
            set
            {
                this.VelocidadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistorialChat", Namespace="http://schemas.datacontract.org/2004/07/ZeusServices")]
    public partial class HistorialChat : object
    {
        
        private int EmisorField;
        
        private System.DateTime FechaField;
        
        private long ID_ChatField;
        
        private string MensajeField;
        
        private int ReceptorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Emisor
        {
            get
            {
                return this.EmisorField;
            }
            set
            {
                this.EmisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID_Chat
        {
            get
            {
                return this.ID_ChatField;
            }
            set
            {
                this.ID_ChatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Receptor
        {
            get
            {
                return this.ReceptorField;
            }
            set
            {
                this.ReceptorField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServiceZeus")]
public interface IServiceZeus
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceZeus/ProbarConexionWs", ReplyAction="http://tempuri.org/IServiceZeus/ProbarConexionWsResponse")]
    System.IAsyncResult BeginProbarConexionWs(System.AsyncCallback callback, object asyncState);
    
    string EndProbarConexionWs(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceZeus/VerificarLogin", ReplyAction="http://tempuri.org/IServiceZeus/VerificarLoginResponse")]
    System.IAsyncResult BeginVerificarLogin(string login, string password, System.AsyncCallback callback, object asyncState);
    
    Acquaint.Native.Droid.EmpleadoDTO EndVerificarLogin(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceZeus/AgregarEmpleado", ReplyAction="http://tempuri.org/IServiceZeus/AgregarEmpleadoResponse")]
    System.IAsyncResult BeginAgregarEmpleado(
                string login, 
                string password, 
                long fechaPassword, 
                long fechaUltimoIngreso, 
                long fechaCreacionUsuario, 
                string nombres, 
                string apellidos, 
                string direccion, 
                decimal salario, 
                string telefonoMovil, 
                string telefonoFijo, 
                string email, 
                short departamentoID, 
                byte[] foto, 
                string identificacion, 
                short cargoID, 
                short grupoEncargadoID, 
                long fechaNacimiento, 
                System.AsyncCallback callback, 
                object asyncState);
    
    void EndAgregarEmpleado(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceZeus/ListaEmpleadosAsignados", ReplyAction="http://tempuri.org/IServiceZeus/ListaEmpleadosAsignadosResponse")]
    System.IAsyncResult BeginListaEmpleadosAsignados(int ID_Grupo_Encargado, System.AsyncCallback callback, object asyncState);
    
    Acquaint.Native.Droid.EmpleadoDTO[] EndListaEmpleadosAsignados(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceZeus/ListaGrupoDeTrabajoConSupervisor", ReplyAction="http://tempuri.org/IServiceZeus/ListaGrupoDeTrabajoConSupervisorResponse")]
    System.IAsyncResult BeginListaGrupoDeTrabajoConSupervisor(int ID_Grupo_Perteneciente, int loginExcluir, System.AsyncCallback callback, object asyncState);
    
    Acquaint.Native.Droid.EmpleadoDTO[] EndListaGrupoDeTrabajoConSupervisor(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceZeus/SubirCoordenadasEmpleados", ReplyAction="http://tempuri.org/IServiceZeus/SubirCoordenadasEmpleadosResponse")]
    System.IAsyncResult BeginSubirCoordenadasEmpleados(int ID, decimal Latitud, decimal Longitud, System.Nullable<decimal> Velocidad, decimal Precision, decimal Bearing, string tiempo, System.AsyncCallback callback, object asyncState);
    
    void EndSubirCoordenadasEmpleados(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceZeus/BajarCoordenadasEmpleados", ReplyAction="http://tempuri.org/IServiceZeus/BajarCoordenadasEmpleadosResponse")]
    System.IAsyncResult BeginBajarCoordenadasEmpleados(long fechaInicial, long fechaFinal, int[] persona, System.AsyncCallback callback, object asyncState);
    
    Acquaint.Native.Droid.UbicacionDTO[] EndBajarCoordenadasEmpleados(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceZeus/ListarMensajes", ReplyAction="http://tempuri.org/IServiceZeus/ListarMensajesResponse")]
    System.IAsyncResult BeginListarMensajes(int emisor, int receptor, System.AsyncCallback callback, object asyncState);
    
    Acquaint.Native.Droid.HistorialChat[] EndListarMensajes(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IServiceZeus/guardarMensajes", ReplyAction="http://tempuri.org/IServiceZeus/guardarMensajesResponse")]
    System.IAsyncResult BeginguardarMensajes(int emisor, int receptor, string mensaje, System.DateTime fecha, System.AsyncCallback callback, object asyncState);
    
    void EndguardarMensajes(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceZeusChannel : IServiceZeus, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ProbarConexionWsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public ProbarConexionWsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class VerificarLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public VerificarLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Acquaint.Native.Droid.EmpleadoDTO Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Acquaint.Native.Droid.EmpleadoDTO)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ListaEmpleadosAsignadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public ListaEmpleadosAsignadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Acquaint.Native.Droid.EmpleadoDTO[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Acquaint.Native.Droid.EmpleadoDTO[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ListaGrupoDeTrabajoConSupervisorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public ListaGrupoDeTrabajoConSupervisorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Acquaint.Native.Droid.EmpleadoDTO[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Acquaint.Native.Droid.EmpleadoDTO[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BajarCoordenadasEmpleadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public BajarCoordenadasEmpleadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Acquaint.Native.Droid.UbicacionDTO[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Acquaint.Native.Droid.UbicacionDTO[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ListarMensajesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public ListarMensajesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public Acquaint.Native.Droid.HistorialChat[] Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((Acquaint.Native.Droid.HistorialChat[])(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceZeusClient : System.ServiceModel.ClientBase<IServiceZeus>, IServiceZeus
{
    
    private BeginOperationDelegate onBeginProbarConexionWsDelegate;
    
    private EndOperationDelegate onEndProbarConexionWsDelegate;
    
    private System.Threading.SendOrPostCallback onProbarConexionWsCompletedDelegate;
    
    private BeginOperationDelegate onBeginVerificarLoginDelegate;
    
    private EndOperationDelegate onEndVerificarLoginDelegate;
    
    private System.Threading.SendOrPostCallback onVerificarLoginCompletedDelegate;
    
    private BeginOperationDelegate onBeginAgregarEmpleadoDelegate;
    
    private EndOperationDelegate onEndAgregarEmpleadoDelegate;
    
    private System.Threading.SendOrPostCallback onAgregarEmpleadoCompletedDelegate;
    
    private BeginOperationDelegate onBeginListaEmpleadosAsignadosDelegate;
    
    private EndOperationDelegate onEndListaEmpleadosAsignadosDelegate;
    
    private System.Threading.SendOrPostCallback onListaEmpleadosAsignadosCompletedDelegate;
    
    private BeginOperationDelegate onBeginListaGrupoDeTrabajoConSupervisorDelegate;
    
    private EndOperationDelegate onEndListaGrupoDeTrabajoConSupervisorDelegate;
    
    private System.Threading.SendOrPostCallback onListaGrupoDeTrabajoConSupervisorCompletedDelegate;
    
    private BeginOperationDelegate onBeginSubirCoordenadasEmpleadosDelegate;
    
    private EndOperationDelegate onEndSubirCoordenadasEmpleadosDelegate;
    
    private System.Threading.SendOrPostCallback onSubirCoordenadasEmpleadosCompletedDelegate;
    
    private BeginOperationDelegate onBeginBajarCoordenadasEmpleadosDelegate;
    
    private EndOperationDelegate onEndBajarCoordenadasEmpleadosDelegate;
    
    private System.Threading.SendOrPostCallback onBajarCoordenadasEmpleadosCompletedDelegate;
    
    private BeginOperationDelegate onBeginListarMensajesDelegate;
    
    private EndOperationDelegate onEndListarMensajesDelegate;
    
    private System.Threading.SendOrPostCallback onListarMensajesCompletedDelegate;
    
    private BeginOperationDelegate onBeginguardarMensajesDelegate;
    
    private EndOperationDelegate onEndguardarMensajesDelegate;
    
    private System.Threading.SendOrPostCallback onguardarMensajesCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public ServiceZeusClient()
    {
    }
    
    public ServiceZeusClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceZeusClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceZeusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceZeusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<ProbarConexionWsCompletedEventArgs> ProbarConexionWsCompleted;
    
    public event System.EventHandler<VerificarLoginCompletedEventArgs> VerificarLoginCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AgregarEmpleadoCompleted;
    
    public event System.EventHandler<ListaEmpleadosAsignadosCompletedEventArgs> ListaEmpleadosAsignadosCompleted;
    
    public event System.EventHandler<ListaGrupoDeTrabajoConSupervisorCompletedEventArgs> ListaGrupoDeTrabajoConSupervisorCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SubirCoordenadasEmpleadosCompleted;
    
    public event System.EventHandler<BajarCoordenadasEmpleadosCompletedEventArgs> BajarCoordenadasEmpleadosCompleted;
    
    public event System.EventHandler<ListarMensajesCompletedEventArgs> ListarMensajesCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> guardarMensajesCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceZeus.BeginProbarConexionWs(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginProbarConexionWs(callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IServiceZeus.EndProbarConexionWs(System.IAsyncResult result)
    {
        return base.Channel.EndProbarConexionWs(result);
    }
    
    private System.IAsyncResult OnBeginProbarConexionWs(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((IServiceZeus)(this)).BeginProbarConexionWs(callback, asyncState);
    }
    
    private object[] OnEndProbarConexionWs(System.IAsyncResult result)
    {
        string retVal = ((IServiceZeus)(this)).EndProbarConexionWs(result);
        return new object[] {
                retVal};
    }
    
    private void OnProbarConexionWsCompleted(object state)
    {
        if ((this.ProbarConexionWsCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ProbarConexionWsCompleted(this, new ProbarConexionWsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ProbarConexionWsAsync()
    {
        this.ProbarConexionWsAsync(null);
    }
    
    public void ProbarConexionWsAsync(object userState)
    {
        if ((this.onBeginProbarConexionWsDelegate == null))
        {
            this.onBeginProbarConexionWsDelegate = new BeginOperationDelegate(this.OnBeginProbarConexionWs);
        }
        if ((this.onEndProbarConexionWsDelegate == null))
        {
            this.onEndProbarConexionWsDelegate = new EndOperationDelegate(this.OnEndProbarConexionWs);
        }
        if ((this.onProbarConexionWsCompletedDelegate == null))
        {
            this.onProbarConexionWsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnProbarConexionWsCompleted);
        }
        base.InvokeAsync(this.onBeginProbarConexionWsDelegate, null, this.onEndProbarConexionWsDelegate, this.onProbarConexionWsCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceZeus.BeginVerificarLogin(string login, string password, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginVerificarLogin(login, password, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Acquaint.Native.Droid.EmpleadoDTO IServiceZeus.EndVerificarLogin(System.IAsyncResult result)
    {
        return base.Channel.EndVerificarLogin(result);
    }
    
    private System.IAsyncResult OnBeginVerificarLogin(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string login = ((string)(inValues[0]));
        string password = ((string)(inValues[1]));
        return ((IServiceZeus)(this)).BeginVerificarLogin(login, password, callback, asyncState);
    }
    
    private object[] OnEndVerificarLogin(System.IAsyncResult result)
    {
        Acquaint.Native.Droid.EmpleadoDTO retVal = ((IServiceZeus)(this)).EndVerificarLogin(result);
        return new object[] {
                retVal};
    }
    
    private void OnVerificarLoginCompleted(object state)
    {
        if ((this.VerificarLoginCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.VerificarLoginCompleted(this, new VerificarLoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void VerificarLoginAsync(string login, string password)
    {
        this.VerificarLoginAsync(login, password, null);
    }
    
    public void VerificarLoginAsync(string login, string password, object userState)
    {
        if ((this.onBeginVerificarLoginDelegate == null))
        {
            this.onBeginVerificarLoginDelegate = new BeginOperationDelegate(this.OnBeginVerificarLogin);
        }
        if ((this.onEndVerificarLoginDelegate == null))
        {
            this.onEndVerificarLoginDelegate = new EndOperationDelegate(this.OnEndVerificarLogin);
        }
        if ((this.onVerificarLoginCompletedDelegate == null))
        {
            this.onVerificarLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnVerificarLoginCompleted);
        }
        base.InvokeAsync(this.onBeginVerificarLoginDelegate, new object[] {
                    login,
                    password}, this.onEndVerificarLoginDelegate, this.onVerificarLoginCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceZeus.BeginAgregarEmpleado(
                string login, 
                string password, 
                long fechaPassword, 
                long fechaUltimoIngreso, 
                long fechaCreacionUsuario, 
                string nombres, 
                string apellidos, 
                string direccion, 
                decimal salario, 
                string telefonoMovil, 
                string telefonoFijo, 
                string email, 
                short departamentoID, 
                byte[] foto, 
                string identificacion, 
                short cargoID, 
                short grupoEncargadoID, 
                long fechaNacimiento, 
                System.AsyncCallback callback, 
                object asyncState)
    {
        return base.Channel.BeginAgregarEmpleado(login, password, fechaPassword, fechaUltimoIngreso, fechaCreacionUsuario, nombres, apellidos, direccion, salario, telefonoMovil, telefonoFijo, email, departamentoID, foto, identificacion, cargoID, grupoEncargadoID, fechaNacimiento, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IServiceZeus.EndAgregarEmpleado(System.IAsyncResult result)
    {
        base.Channel.EndAgregarEmpleado(result);
    }
    
    private System.IAsyncResult OnBeginAgregarEmpleado(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string login = ((string)(inValues[0]));
        string password = ((string)(inValues[1]));
        long fechaPassword = ((long)(inValues[2]));
        long fechaUltimoIngreso = ((long)(inValues[3]));
        long fechaCreacionUsuario = ((long)(inValues[4]));
        string nombres = ((string)(inValues[5]));
        string apellidos = ((string)(inValues[6]));
        string direccion = ((string)(inValues[7]));
        decimal salario = ((decimal)(inValues[8]));
        string telefonoMovil = ((string)(inValues[9]));
        string telefonoFijo = ((string)(inValues[10]));
        string email = ((string)(inValues[11]));
        short departamentoID = ((short)(inValues[12]));
        byte[] foto = ((byte[])(inValues[13]));
        string identificacion = ((string)(inValues[14]));
        short cargoID = ((short)(inValues[15]));
        short grupoEncargadoID = ((short)(inValues[16]));
        long fechaNacimiento = ((long)(inValues[17]));
        return ((IServiceZeus)(this)).BeginAgregarEmpleado(login, password, fechaPassword, fechaUltimoIngreso, fechaCreacionUsuario, nombres, apellidos, direccion, salario, telefonoMovil, telefonoFijo, email, departamentoID, foto, identificacion, cargoID, grupoEncargadoID, fechaNacimiento, callback, asyncState);
    }
    
    private object[] OnEndAgregarEmpleado(System.IAsyncResult result)
    {
        ((IServiceZeus)(this)).EndAgregarEmpleado(result);
        return null;
    }
    
    private void OnAgregarEmpleadoCompleted(object state)
    {
        if ((this.AgregarEmpleadoCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.AgregarEmpleadoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void AgregarEmpleadoAsync(
                string login, 
                string password, 
                long fechaPassword, 
                long fechaUltimoIngreso, 
                long fechaCreacionUsuario, 
                string nombres, 
                string apellidos, 
                string direccion, 
                decimal salario, 
                string telefonoMovil, 
                string telefonoFijo, 
                string email, 
                short departamentoID, 
                byte[] foto, 
                string identificacion, 
                short cargoID, 
                short grupoEncargadoID, 
                long fechaNacimiento)
    {
        this.AgregarEmpleadoAsync(login, password, fechaPassword, fechaUltimoIngreso, fechaCreacionUsuario, nombres, apellidos, direccion, salario, telefonoMovil, telefonoFijo, email, departamentoID, foto, identificacion, cargoID, grupoEncargadoID, fechaNacimiento, null);
    }
    
    public void AgregarEmpleadoAsync(
                string login, 
                string password, 
                long fechaPassword, 
                long fechaUltimoIngreso, 
                long fechaCreacionUsuario, 
                string nombres, 
                string apellidos, 
                string direccion, 
                decimal salario, 
                string telefonoMovil, 
                string telefonoFijo, 
                string email, 
                short departamentoID, 
                byte[] foto, 
                string identificacion, 
                short cargoID, 
                short grupoEncargadoID, 
                long fechaNacimiento, 
                object userState)
    {
        if ((this.onBeginAgregarEmpleadoDelegate == null))
        {
            this.onBeginAgregarEmpleadoDelegate = new BeginOperationDelegate(this.OnBeginAgregarEmpleado);
        }
        if ((this.onEndAgregarEmpleadoDelegate == null))
        {
            this.onEndAgregarEmpleadoDelegate = new EndOperationDelegate(this.OnEndAgregarEmpleado);
        }
        if ((this.onAgregarEmpleadoCompletedDelegate == null))
        {
            this.onAgregarEmpleadoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAgregarEmpleadoCompleted);
        }
        base.InvokeAsync(this.onBeginAgregarEmpleadoDelegate, new object[] {
                    login,
                    password,
                    fechaPassword,
                    fechaUltimoIngreso,
                    fechaCreacionUsuario,
                    nombres,
                    apellidos,
                    direccion,
                    salario,
                    telefonoMovil,
                    telefonoFijo,
                    email,
                    departamentoID,
                    foto,
                    identificacion,
                    cargoID,
                    grupoEncargadoID,
                    fechaNacimiento}, this.onEndAgregarEmpleadoDelegate, this.onAgregarEmpleadoCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceZeus.BeginListaEmpleadosAsignados(int ID_Grupo_Encargado, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginListaEmpleadosAsignados(ID_Grupo_Encargado, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Acquaint.Native.Droid.EmpleadoDTO[] IServiceZeus.EndListaEmpleadosAsignados(System.IAsyncResult result)
    {
        return base.Channel.EndListaEmpleadosAsignados(result);
    }
    
    private System.IAsyncResult OnBeginListaEmpleadosAsignados(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int ID_Grupo_Encargado = ((int)(inValues[0]));
        return ((IServiceZeus)(this)).BeginListaEmpleadosAsignados(ID_Grupo_Encargado, callback, asyncState);
    }
    
    private object[] OnEndListaEmpleadosAsignados(System.IAsyncResult result)
    {
        Acquaint.Native.Droid.EmpleadoDTO[] retVal = ((IServiceZeus)(this)).EndListaEmpleadosAsignados(result);
        return new object[] {
                retVal};
    }
    
    private void OnListaEmpleadosAsignadosCompleted(object state)
    {
        if ((this.ListaEmpleadosAsignadosCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ListaEmpleadosAsignadosCompleted(this, new ListaEmpleadosAsignadosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ListaEmpleadosAsignadosAsync(int ID_Grupo_Encargado)
    {
        this.ListaEmpleadosAsignadosAsync(ID_Grupo_Encargado, null);
    }
    
    public void ListaEmpleadosAsignadosAsync(int ID_Grupo_Encargado, object userState)
    {
        if ((this.onBeginListaEmpleadosAsignadosDelegate == null))
        {
            this.onBeginListaEmpleadosAsignadosDelegate = new BeginOperationDelegate(this.OnBeginListaEmpleadosAsignados);
        }
        if ((this.onEndListaEmpleadosAsignadosDelegate == null))
        {
            this.onEndListaEmpleadosAsignadosDelegate = new EndOperationDelegate(this.OnEndListaEmpleadosAsignados);
        }
        if ((this.onListaEmpleadosAsignadosCompletedDelegate == null))
        {
            this.onListaEmpleadosAsignadosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListaEmpleadosAsignadosCompleted);
        }
        base.InvokeAsync(this.onBeginListaEmpleadosAsignadosDelegate, new object[] {
                    ID_Grupo_Encargado}, this.onEndListaEmpleadosAsignadosDelegate, this.onListaEmpleadosAsignadosCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceZeus.BeginListaGrupoDeTrabajoConSupervisor(int ID_Grupo_Perteneciente, int loginExcluir, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginListaGrupoDeTrabajoConSupervisor(ID_Grupo_Perteneciente, loginExcluir, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Acquaint.Native.Droid.EmpleadoDTO[] IServiceZeus.EndListaGrupoDeTrabajoConSupervisor(System.IAsyncResult result)
    {
        return base.Channel.EndListaGrupoDeTrabajoConSupervisor(result);
    }
    
    private System.IAsyncResult OnBeginListaGrupoDeTrabajoConSupervisor(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int ID_Grupo_Perteneciente = ((int)(inValues[0]));
        int loginExcluir = ((int)(inValues[1]));
        return ((IServiceZeus)(this)).BeginListaGrupoDeTrabajoConSupervisor(ID_Grupo_Perteneciente, loginExcluir, callback, asyncState);
    }
    
    private object[] OnEndListaGrupoDeTrabajoConSupervisor(System.IAsyncResult result)
    {
        Acquaint.Native.Droid.EmpleadoDTO[] retVal = ((IServiceZeus)(this)).EndListaGrupoDeTrabajoConSupervisor(result);
        return new object[] {
                retVal};
    }
    
    private void OnListaGrupoDeTrabajoConSupervisorCompleted(object state)
    {
        if ((this.ListaGrupoDeTrabajoConSupervisorCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ListaGrupoDeTrabajoConSupervisorCompleted(this, new ListaGrupoDeTrabajoConSupervisorCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ListaGrupoDeTrabajoConSupervisorAsync(int ID_Grupo_Perteneciente, int loginExcluir)
    {
        this.ListaGrupoDeTrabajoConSupervisorAsync(ID_Grupo_Perteneciente, loginExcluir, null);
    }
    
    public void ListaGrupoDeTrabajoConSupervisorAsync(int ID_Grupo_Perteneciente, int loginExcluir, object userState)
    {
        if ((this.onBeginListaGrupoDeTrabajoConSupervisorDelegate == null))
        {
            this.onBeginListaGrupoDeTrabajoConSupervisorDelegate = new BeginOperationDelegate(this.OnBeginListaGrupoDeTrabajoConSupervisor);
        }
        if ((this.onEndListaGrupoDeTrabajoConSupervisorDelegate == null))
        {
            this.onEndListaGrupoDeTrabajoConSupervisorDelegate = new EndOperationDelegate(this.OnEndListaGrupoDeTrabajoConSupervisor);
        }
        if ((this.onListaGrupoDeTrabajoConSupervisorCompletedDelegate == null))
        {
            this.onListaGrupoDeTrabajoConSupervisorCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListaGrupoDeTrabajoConSupervisorCompleted);
        }
        base.InvokeAsync(this.onBeginListaGrupoDeTrabajoConSupervisorDelegate, new object[] {
                    ID_Grupo_Perteneciente,
                    loginExcluir}, this.onEndListaGrupoDeTrabajoConSupervisorDelegate, this.onListaGrupoDeTrabajoConSupervisorCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceZeus.BeginSubirCoordenadasEmpleados(int ID, decimal Latitud, decimal Longitud, System.Nullable<decimal> Velocidad, decimal Precision, decimal Bearing, string tiempo, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSubirCoordenadasEmpleados(ID, Latitud, Longitud, Velocidad, Precision, Bearing, tiempo, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IServiceZeus.EndSubirCoordenadasEmpleados(System.IAsyncResult result)
    {
        base.Channel.EndSubirCoordenadasEmpleados(result);
    }
    
    private System.IAsyncResult OnBeginSubirCoordenadasEmpleados(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int ID = ((int)(inValues[0]));
        decimal Latitud = ((decimal)(inValues[1]));
        decimal Longitud = ((decimal)(inValues[2]));
        System.Nullable<decimal> Velocidad = ((System.Nullable<decimal>)(inValues[3]));
        decimal Precision = ((decimal)(inValues[4]));
        decimal Bearing = ((decimal)(inValues[5]));
        string tiempo = ((string)(inValues[6]));
        return ((IServiceZeus)(this)).BeginSubirCoordenadasEmpleados(ID, Latitud, Longitud, Velocidad, Precision, Bearing, tiempo, callback, asyncState);
    }
    
    private object[] OnEndSubirCoordenadasEmpleados(System.IAsyncResult result)
    {
        ((IServiceZeus)(this)).EndSubirCoordenadasEmpleados(result);
        return null;
    }
    
    private void OnSubirCoordenadasEmpleadosCompleted(object state)
    {
        if ((this.SubirCoordenadasEmpleadosCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.SubirCoordenadasEmpleadosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void SubirCoordenadasEmpleadosAsync(int ID, decimal Latitud, decimal Longitud, System.Nullable<decimal> Velocidad, decimal Precision, decimal Bearing, string tiempo)
    {
        this.SubirCoordenadasEmpleadosAsync(ID, Latitud, Longitud, Velocidad, Precision, Bearing, tiempo, null);
    }
    
    public void SubirCoordenadasEmpleadosAsync(int ID, decimal Latitud, decimal Longitud, System.Nullable<decimal> Velocidad, decimal Precision, decimal Bearing, string tiempo, object userState)
    {
        if ((this.onBeginSubirCoordenadasEmpleadosDelegate == null))
        {
            this.onBeginSubirCoordenadasEmpleadosDelegate = new BeginOperationDelegate(this.OnBeginSubirCoordenadasEmpleados);
        }
        if ((this.onEndSubirCoordenadasEmpleadosDelegate == null))
        {
            this.onEndSubirCoordenadasEmpleadosDelegate = new EndOperationDelegate(this.OnEndSubirCoordenadasEmpleados);
        }
        if ((this.onSubirCoordenadasEmpleadosCompletedDelegate == null))
        {
            this.onSubirCoordenadasEmpleadosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSubirCoordenadasEmpleadosCompleted);
        }
        base.InvokeAsync(this.onBeginSubirCoordenadasEmpleadosDelegate, new object[] {
                    ID,
                    Latitud,
                    Longitud,
                    Velocidad,
                    Precision,
                    Bearing,
                    tiempo}, this.onEndSubirCoordenadasEmpleadosDelegate, this.onSubirCoordenadasEmpleadosCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceZeus.BeginBajarCoordenadasEmpleados(long fechaInicial, long fechaFinal, int[] persona, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginBajarCoordenadasEmpleados(fechaInicial, fechaFinal, persona, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Acquaint.Native.Droid.UbicacionDTO[] IServiceZeus.EndBajarCoordenadasEmpleados(System.IAsyncResult result)
    {
        return base.Channel.EndBajarCoordenadasEmpleados(result);
    }
    
    private System.IAsyncResult OnBeginBajarCoordenadasEmpleados(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        long fechaInicial = ((long)(inValues[0]));
        long fechaFinal = ((long)(inValues[1]));
        int[] persona = ((int[])(inValues[2]));
        return ((IServiceZeus)(this)).BeginBajarCoordenadasEmpleados(fechaInicial, fechaFinal, persona, callback, asyncState);
    }
    
    private object[] OnEndBajarCoordenadasEmpleados(System.IAsyncResult result)
    {
        Acquaint.Native.Droid.UbicacionDTO[] retVal = ((IServiceZeus)(this)).EndBajarCoordenadasEmpleados(result);
        return new object[] {
                retVal};
    }
    
    private void OnBajarCoordenadasEmpleadosCompleted(object state)
    {
        if ((this.BajarCoordenadasEmpleadosCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.BajarCoordenadasEmpleadosCompleted(this, new BajarCoordenadasEmpleadosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void BajarCoordenadasEmpleadosAsync(long fechaInicial, long fechaFinal, int[] persona)
    {
        this.BajarCoordenadasEmpleadosAsync(fechaInicial, fechaFinal, persona, null);
    }
    
    public void BajarCoordenadasEmpleadosAsync(long fechaInicial, long fechaFinal, int[] persona, object userState)
    {
        if ((this.onBeginBajarCoordenadasEmpleadosDelegate == null))
        {
            this.onBeginBajarCoordenadasEmpleadosDelegate = new BeginOperationDelegate(this.OnBeginBajarCoordenadasEmpleados);
        }
        if ((this.onEndBajarCoordenadasEmpleadosDelegate == null))
        {
            this.onEndBajarCoordenadasEmpleadosDelegate = new EndOperationDelegate(this.OnEndBajarCoordenadasEmpleados);
        }
        if ((this.onBajarCoordenadasEmpleadosCompletedDelegate == null))
        {
            this.onBajarCoordenadasEmpleadosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBajarCoordenadasEmpleadosCompleted);
        }
        base.InvokeAsync(this.onBeginBajarCoordenadasEmpleadosDelegate, new object[] {
                    fechaInicial,
                    fechaFinal,
                    persona}, this.onEndBajarCoordenadasEmpleadosDelegate, this.onBajarCoordenadasEmpleadosCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceZeus.BeginListarMensajes(int emisor, int receptor, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginListarMensajes(emisor, receptor, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    Acquaint.Native.Droid.HistorialChat[] IServiceZeus.EndListarMensajes(System.IAsyncResult result)
    {
        return base.Channel.EndListarMensajes(result);
    }
    
    private System.IAsyncResult OnBeginListarMensajes(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int emisor = ((int)(inValues[0]));
        int receptor = ((int)(inValues[1]));
        return ((IServiceZeus)(this)).BeginListarMensajes(emisor, receptor, callback, asyncState);
    }
    
    private object[] OnEndListarMensajes(System.IAsyncResult result)
    {
        Acquaint.Native.Droid.HistorialChat[] retVal = ((IServiceZeus)(this)).EndListarMensajes(result);
        return new object[] {
                retVal};
    }
    
    private void OnListarMensajesCompleted(object state)
    {
        if ((this.ListarMensajesCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.ListarMensajesCompleted(this, new ListarMensajesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void ListarMensajesAsync(int emisor, int receptor)
    {
        this.ListarMensajesAsync(emisor, receptor, null);
    }
    
    public void ListarMensajesAsync(int emisor, int receptor, object userState)
    {
        if ((this.onBeginListarMensajesDelegate == null))
        {
            this.onBeginListarMensajesDelegate = new BeginOperationDelegate(this.OnBeginListarMensajes);
        }
        if ((this.onEndListarMensajesDelegate == null))
        {
            this.onEndListarMensajesDelegate = new EndOperationDelegate(this.OnEndListarMensajes);
        }
        if ((this.onListarMensajesCompletedDelegate == null))
        {
            this.onListarMensajesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListarMensajesCompleted);
        }
        base.InvokeAsync(this.onBeginListarMensajesDelegate, new object[] {
                    emisor,
                    receptor}, this.onEndListarMensajesDelegate, this.onListarMensajesCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IServiceZeus.BeginguardarMensajes(int emisor, int receptor, string mensaje, System.DateTime fecha, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginguardarMensajes(emisor, receptor, mensaje, fecha, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    void IServiceZeus.EndguardarMensajes(System.IAsyncResult result)
    {
        base.Channel.EndguardarMensajes(result);
    }
    
    private System.IAsyncResult OnBeginguardarMensajes(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        int emisor = ((int)(inValues[0]));
        int receptor = ((int)(inValues[1]));
        string mensaje = ((string)(inValues[2]));
        System.DateTime fecha = ((System.DateTime)(inValues[3]));
        return ((IServiceZeus)(this)).BeginguardarMensajes(emisor, receptor, mensaje, fecha, callback, asyncState);
    }
    
    private object[] OnEndguardarMensajes(System.IAsyncResult result)
    {
        ((IServiceZeus)(this)).EndguardarMensajes(result);
        return null;
    }
    
    private void OnguardarMensajesCompleted(object state)
    {
        if ((this.guardarMensajesCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.guardarMensajesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void guardarMensajesAsync(int emisor, int receptor, string mensaje, System.DateTime fecha)
    {
        this.guardarMensajesAsync(emisor, receptor, mensaje, fecha, null);
    }
    
    public void guardarMensajesAsync(int emisor, int receptor, string mensaje, System.DateTime fecha, object userState)
    {
        if ((this.onBeginguardarMensajesDelegate == null))
        {
            this.onBeginguardarMensajesDelegate = new BeginOperationDelegate(this.OnBeginguardarMensajes);
        }
        if ((this.onEndguardarMensajesDelegate == null))
        {
            this.onEndguardarMensajesDelegate = new EndOperationDelegate(this.OnEndguardarMensajes);
        }
        if ((this.onguardarMensajesCompletedDelegate == null))
        {
            this.onguardarMensajesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnguardarMensajesCompleted);
        }
        base.InvokeAsync(this.onBeginguardarMensajesDelegate, new object[] {
                    emisor,
                    receptor,
                    mensaje,
                    fecha}, this.onEndguardarMensajesDelegate, this.onguardarMensajesCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IServiceZeus CreateChannel()
    {
        return new ServiceZeusClientChannel(this);
    }
    
    private class ServiceZeusClientChannel : ChannelBase<IServiceZeus>, IServiceZeus
    {
        
        public ServiceZeusClientChannel(System.ServiceModel.ClientBase<IServiceZeus> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginProbarConexionWs(System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[0];
            System.IAsyncResult _result = base.BeginInvoke("ProbarConexionWs", _args, callback, asyncState);
            return _result;
        }
        
        public string EndProbarConexionWs(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("ProbarConexionWs", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginVerificarLogin(string login, string password, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = login;
            _args[1] = password;
            System.IAsyncResult _result = base.BeginInvoke("VerificarLogin", _args, callback, asyncState);
            return _result;
        }
        
        public Acquaint.Native.Droid.EmpleadoDTO EndVerificarLogin(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            Acquaint.Native.Droid.EmpleadoDTO _result = ((Acquaint.Native.Droid.EmpleadoDTO)(base.EndInvoke("VerificarLogin", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginAgregarEmpleado(
                    string login, 
                    string password, 
                    long fechaPassword, 
                    long fechaUltimoIngreso, 
                    long fechaCreacionUsuario, 
                    string nombres, 
                    string apellidos, 
                    string direccion, 
                    decimal salario, 
                    string telefonoMovil, 
                    string telefonoFijo, 
                    string email, 
                    short departamentoID, 
                    byte[] foto, 
                    string identificacion, 
                    short cargoID, 
                    short grupoEncargadoID, 
                    long fechaNacimiento, 
                    System.AsyncCallback callback, 
                    object asyncState)
        {
            object[] _args = new object[18];
            _args[0] = login;
            _args[1] = password;
            _args[2] = fechaPassword;
            _args[3] = fechaUltimoIngreso;
            _args[4] = fechaCreacionUsuario;
            _args[5] = nombres;
            _args[6] = apellidos;
            _args[7] = direccion;
            _args[8] = salario;
            _args[9] = telefonoMovil;
            _args[10] = telefonoFijo;
            _args[11] = email;
            _args[12] = departamentoID;
            _args[13] = foto;
            _args[14] = identificacion;
            _args[15] = cargoID;
            _args[16] = grupoEncargadoID;
            _args[17] = fechaNacimiento;
            System.IAsyncResult _result = base.BeginInvoke("AgregarEmpleado", _args, callback, asyncState);
            return _result;
        }
        
        public void EndAgregarEmpleado(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("AgregarEmpleado", _args, result);
        }
        
        public System.IAsyncResult BeginListaEmpleadosAsignados(int ID_Grupo_Encargado, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = ID_Grupo_Encargado;
            System.IAsyncResult _result = base.BeginInvoke("ListaEmpleadosAsignados", _args, callback, asyncState);
            return _result;
        }
        
        public Acquaint.Native.Droid.EmpleadoDTO[] EndListaEmpleadosAsignados(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            Acquaint.Native.Droid.EmpleadoDTO[] _result = ((Acquaint.Native.Droid.EmpleadoDTO[])(base.EndInvoke("ListaEmpleadosAsignados", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginListaGrupoDeTrabajoConSupervisor(int ID_Grupo_Perteneciente, int loginExcluir, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = ID_Grupo_Perteneciente;
            _args[1] = loginExcluir;
            System.IAsyncResult _result = base.BeginInvoke("ListaGrupoDeTrabajoConSupervisor", _args, callback, asyncState);
            return _result;
        }
        
        public Acquaint.Native.Droid.EmpleadoDTO[] EndListaGrupoDeTrabajoConSupervisor(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            Acquaint.Native.Droid.EmpleadoDTO[] _result = ((Acquaint.Native.Droid.EmpleadoDTO[])(base.EndInvoke("ListaGrupoDeTrabajoConSupervisor", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginSubirCoordenadasEmpleados(int ID, decimal Latitud, decimal Longitud, System.Nullable<decimal> Velocidad, decimal Precision, decimal Bearing, string tiempo, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[7];
            _args[0] = ID;
            _args[1] = Latitud;
            _args[2] = Longitud;
            _args[3] = Velocidad;
            _args[4] = Precision;
            _args[5] = Bearing;
            _args[6] = tiempo;
            System.IAsyncResult _result = base.BeginInvoke("SubirCoordenadasEmpleados", _args, callback, asyncState);
            return _result;
        }
        
        public void EndSubirCoordenadasEmpleados(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("SubirCoordenadasEmpleados", _args, result);
        }
        
        public System.IAsyncResult BeginBajarCoordenadasEmpleados(long fechaInicial, long fechaFinal, int[] persona, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[3];
            _args[0] = fechaInicial;
            _args[1] = fechaFinal;
            _args[2] = persona;
            System.IAsyncResult _result = base.BeginInvoke("BajarCoordenadasEmpleados", _args, callback, asyncState);
            return _result;
        }
        
        public Acquaint.Native.Droid.UbicacionDTO[] EndBajarCoordenadasEmpleados(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            Acquaint.Native.Droid.UbicacionDTO[] _result = ((Acquaint.Native.Droid.UbicacionDTO[])(base.EndInvoke("BajarCoordenadasEmpleados", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginListarMensajes(int emisor, int receptor, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = emisor;
            _args[1] = receptor;
            System.IAsyncResult _result = base.BeginInvoke("ListarMensajes", _args, callback, asyncState);
            return _result;
        }
        
        public Acquaint.Native.Droid.HistorialChat[] EndListarMensajes(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            Acquaint.Native.Droid.HistorialChat[] _result = ((Acquaint.Native.Droid.HistorialChat[])(base.EndInvoke("ListarMensajes", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginguardarMensajes(int emisor, int receptor, string mensaje, System.DateTime fecha, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[4];
            _args[0] = emisor;
            _args[1] = receptor;
            _args[2] = mensaje;
            _args[3] = fecha;
            System.IAsyncResult _result = base.BeginInvoke("guardarMensajes", _args, callback, asyncState);
            return _result;
        }
        
        public void EndguardarMensajes(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            base.EndInvoke("guardarMensajes", _args, result);
        }
    }
}
